### ISSUE TITLE
Could not pass event BlockPlaceEvent to HeadDrops v1.5

### ISSUE THREAD

**Issue by DestinTech** [evancolewright/HeadDrops#5] opened 2022-05-20 17:34 UTC
### Plugin Version
1.5

### Server Version
Purpur(paper drop-in replacment) 1.18.2 latest

### StackTrace
**20.05 17:17:57 [Server] ERROR Could not pass event BlockPlaceEvent to HeadDrops v1.5
20.05 17:17:57 [Server] INFO java.lang.NullPointerException: ItemStack can't be null/Air! This is not a NBTAPI bug!
20.05 17:17:57 [Server] INFO at com.github.evancolewright.nbtapi.NBTItem.<init>(NBTItem.java:42) ~[HeadDrops.jar:?]
20.05 17:17:57 [Server] INFO at com.github.evancolewright.nbtapi.NBTItem.<init>(NBTItem.java:28) ~[HeadDrops.jar:?]
20.05 17:17:57 [Server] INFO at com.github.evancolewright.headdrops.api.HeadDropsAPI.isPlayerHead(HeadDropsAPI.java:17) ~[HeadDrops.jar:?]
20.05 17:17:57 [Server] INFO at com.github.evancolewright.headdrops.HeadDropsListeners.onHeadPlace(HeadDropsListeners.java:63) ~[HeadDrops.jar:?]
20.05 17:17:57 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor49.execute(Unknown Source) ~[?:?]
20.05 17:17:57 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
20.05 17:17:57 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:git-Purpur-"0939dde"]
20.05 17:17:57 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
20.05 17:17:57 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:671) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
20.05 17:17:57 [Server] INFO at org.bukkit.craftbukkit.v1_18_R2.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:393) ~[purpur-1.18.2.jar:git-Purpur-"0939dde"]
20.05 17:17:57 [Server] INFO at net.minecraft.world.item.ItemStack.useOn(ItemStack.java:383) ~[purpur-1.18.2.jar:git-Purpur-"0939dde"]
20.05 17:17:57 [Server] INFO at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:627) ~[?:?]
20.05 17:17:57 [Server] INFO at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1924) ~[?:?]
20.05 17:17:57 [Server] INFO at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:33) ~[?:?]
20.05 17:17:57 [Server] INFO at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.a(ServerboundUseItemOnPacket.java:9) ~[?:?]
20.05 17:17:57 [Server] INFO at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
20.05 17:18:00 [Server] INFO at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.18.2.jar:git-Purpur-"0939dde"]
20.05 17:18:00 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
20.05 17:18:00 [Server] INFO at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
20.05 17:18:00 [Server] INFO at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1426) ~[purpur-1.18.2.jar:git-Purpur-"0939dde"]
20.05 17:18:00 [Server] INFO at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188) ~[purpur-1.18.2.jar:git-Purpur-"0939dde"]
20.05 17:18:00 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
20.05 17:18:00 [Server] INFO at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1403) ~[purpur-1.18.2.jar:git-Purpur-"0939dde"]
20.05 17:18:00 [Server] INFO at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1396) ~[purpur-1.18.2.jar:git-Purpur-"0939dde"]
20.05 17:18:00 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
20.05 17:18:00 [Server] INFO at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1374) ~[purpur-1.18.2.jar:git-Purpur-"0939dde"]
20.05 17:18:00 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1256) ~[purpur-1.18.2.jar:git-Purpur-"0939dde"]
20.05 17:18:00 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:320) ~[purpur-1.18.2.jar:git-Purpur-"0939dde"]
20.05 17:18:00 [Server] INFO at java.lang.Thread.run(Thread.java:831) ~[?:?]**
### Steps to Reproduce
Unsure, appeared after upgrade to 1.5, could be related to purpur?

**Comment by TreeOfSelf** [comment] 2022-05-20 18:34
Same thing here, using pufferfish (paper fork) 

`[18:28:01 ERROR]: Could not pass event BlockPlaceEvent to HeadDrops v1.5
java.lang.NullPointerException: ItemStack can't be null/Air! This is not a NBTAPI bug!
        at com.github.evancolewright.headdrops.nbtapi.NBTItem.<init>(NBTItem.java:42) ~[HeadDrops-v1.5.jar:?]
        at com.github.evancolewright.headdrops.nbtapi.NBTItem.<init>(NBTItem.java:28) ~[HeadDrops-v1.5.jar:?]
        at com.github.evancolewright.headdrops.api.HeadDropsAPI.isPlayerHead(HeadDropsAPI.java:17) ~[HeadDrops-v1.5.jar:?]
        at com.github.evancolewright.headdrops.HeadDropsListeners.onHeadPlace(HeadDropsListeners.java:63) ~[HeadDrops-v1.5.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor42.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[pufferfish-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[pufferfish-api-1.18.2-R0.1-SNAPSHOT.jar:git-Pufferfish-67]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[pufferfish-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:671) ~[pufferfish-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:393) ~[pufferfish-1.18.2.jar:git-Pufferfish-67]
        at net.minecraft.world.item.ItemStack.useOn(ItemStack.java:383) ~[pufferfish-1.18.2.jar:git-Pufferfish-67]
        at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:625) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1852) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:33) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.a(ServerboundUseItemOnPacket.java:9) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[pufferfish-1.18.2.jar:git-Pufferfish-67]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1401) ~[pufferfish-1.18.2.jar:git-Pufferfish-67]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188) ~[pufferfish-1.18.2.jar:git-Pufferfish-67]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1378) ~[pufferfish-1.18.2.jar:git-Pufferfish-67]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1371) ~[pufferfish-1.18.2.jar:git-Pufferfish-67]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1349) ~[pufferfish-1.18.2.jar:git-Pufferfish-67]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1231) ~[pufferfish-1.18.2.jar:git-Pufferfish-67]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:317) ~[pufferfish-1.18.2.jar:git-Pufferfish-67]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]`

**Comment by evancolewright** [comment] 2022-05-20 22:21
Thank you both for reporting this issue. 

This seems to be happening when a player places any block using their off-hand.  I believe I have found the cause and will release a patch later tonight.

**Comment by TreeOfSelf** [comment] 2022-05-20 22:27
THANK YOU!! THANK YOU!!! BEST PLUGIN DEVELOEPR EVER!!

**Comment by evancolewright** [comment] 2022-05-21 02:37
I believe this issue is now resolved.  Try and download the new version and make sure the error does not still occur.  Let me know if it works for you, and I will close this issue.

https://www.spigotmc.org/resources/headdrops-1-8-1-18.15964/updates

Thanks again!

**Comment by RealTriassic** [comment] 2022-05-21 10:29
This is still happening for me.


Server Info:
Running Purpur 1.18.2 build 1625
Upgraded from HeadDrops 1.4 by regenerating configuration.

```
[10:28:00 ERROR]: Could not pass event BlockPlaceEvent to HeadDrops v1.5
java.lang.NullPointerException: ItemStack can't be null/Air! This is not a NBTAPI bug!
        at com.github.evancolewright.headdrops.nbtapi.NBTItem.<init>(NBTItem.java:42) ~[HeadDrops-1.5.1.jar:?]
        at com.github.evancolewright.headdrops.nbtapi.NBTItem.<init>(NBTItem.java:28) ~[HeadDrops-1.5.1.jar:?]
        at com.github.evancolewright.headdrops.api.HeadDropsAPI.isPlayerHead(HeadDropsAPI.java:17) ~[HeadDrops-1.5.1.jar:?]
        at com.github.evancolewright.headdrops.HeadDropsListeners.onHeadPlace(HeadDropsListeners.java:64) ~[HeadDrops-1.5.1.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor70.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:git-Purpur-1625]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:671) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:393) ~[purpur-1.18.2.jar:git-Purpur-1625]
        at net.minecraft.world.item.ItemStack.useOn(ItemStack.java:383) ~[purpur-1.18.2.jar:git-Purpur-1625]
        at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:627) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1924) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:33) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.a(ServerboundUseItemOnPacket.java:9) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.18.2.jar:git-Purpur-1625]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1426) ~[purpur-1.18.2.jar:git-Purpur-1625]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188) ~[purpur-1.18.2.jar:git-Purpur-1625]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1403) ~[purpur-1.18.2.jar:git-Purpur-1625]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1396) ~[purpur-1.18.2.jar:git-Purpur-1625]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1374) ~[purpur-1.18.2.jar:git-Purpur-1625]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1256) ~[purpur-1.18.2.jar:git-Purpur-1625]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:320) ~[purpur-1.18.2.jar:git-Purpur-1625]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by evancolewright** [comment] 2022-05-21 18:27
> This is still happening for me.
> 
> Server Info: Running Purpur 1.18.2 build 1625 Upgraded from HeadDrops 1.4 by regenerating configuration.
> 
> ```
> [10:28:00 ERROR]: Could not pass event BlockPlaceEvent to HeadDrops v1.5
> java.lang.NullPointerException: ItemStack can't be null/Air! This is not a NBTAPI bug!
>         at com.github.evancolewright.headdrops.nbtapi.NBTItem.<init>(NBTItem.java:42) ~[HeadDrops-1.5.1.jar:?]
>         at com.github.evancolewright.headdrops.nbtapi.NBTItem.<init>(NBTItem.java:28) ~[HeadDrops-1.5.1.jar:?]
>         at com.github.evancolewright.headdrops.api.HeadDropsAPI.isPlayerHead(HeadDropsAPI.java:17) ~[HeadDrops-1.5.1.jar:?]
>         at com.github.evancolewright.headdrops.HeadDropsListeners.onHeadPlace(HeadDropsListeners.java:64) ~[HeadDrops-1.5.1.jar:?]
>         at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor70.execute(Unknown Source) ~[?:?]
>         at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
>         at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:git-Purpur-1625]
>         at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
>         at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:671) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
>         at org.bukkit.craftbukkit.v1_18_R2.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:393) ~[purpur-1.18.2.jar:git-Purpur-1625]
>         at net.minecraft.world.item.ItemStack.useOn(ItemStack.java:383) ~[purpur-1.18.2.jar:git-Purpur-1625]
>         at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:627) ~[?:?]
>         at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1924) ~[?:?]
>         at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:33) ~[?:?]
>         at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.a(ServerboundUseItemOnPacket.java:9) ~[?:?]
>         at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
>         at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.18.2.jar:git-Purpur-1625]
>         at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
>         at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
>         at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1426) ~[purpur-1.18.2.jar:git-Purpur-1625]
>         at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188) ~[purpur-1.18.2.jar:git-Purpur-1625]
>         at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
>         at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1403) ~[purpur-1.18.2.jar:git-Purpur-1625]
>         at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1396) ~[purpur-1.18.2.jar:git-Purpur-1625]
>         at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
>         at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1374) ~[purpur-1.18.2.jar:git-Purpur-1625]
>         at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1256) ~[purpur-1.18.2.jar:git-Purpur-1625]
>         at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:320) ~[purpur-1.18.2.jar:git-Purpur-1625]
>         at java.lang.Thread.run(Thread.java:833) ~[?:?]
> ```

I am unable to reproduce this bug anymore as of v1.5.2.  Download the most recent patch from the resource page on Spigot. Check the console on the server start to make sure it says you're running the correct HeadDrops version (1.5.2).  

If it's still occurring for you at that point, reply back on this issue on how you are able to reproduce this bug.

https://www.spigotmc.org/resources/headdrops-1-8-1-18.15964/

**Comment by RealTriassic** [comment] 2022-05-21 20:30
I can confirm the issue no longer occurs on the latest (1.5.2) version, thank you for fixing the issue!

**Comment by evancolewright** [comment] 2022-05-21 21:01
> I can confirm the issue no longer occurs on the latest (1.5.2) version, thank you for fixing the issue!

No problem, thank you for reporting.

**Closed by evancolewright** 2022-05-21 21:01 UTC
